name: 'Adjacent: Related Repos Recommender'
description: 'Discover and showcase related repositories automatically. Uses GitHub topics and README similarity to find and add related repos to your project documentation.'
author: 'Gaurav Sood'
branding:
  icon: link-2
  color: blue
inputs:
  repo:
    description: 'Target repository in owner/name format (e.g., soodoku/fastsql)'
    required: false
    default: ${{ github.repository }}
  token:
    description: 'GitHub token for API access'
    required: true
    default: ''
  similarity_method:
    description: 'Method to find similar repositories: topics, readme, or combined'
    required: false
    default: 'combined'
  topic_weight:
    description: 'Weight for topics in combined similarity method (0-1)'
    required: false
    default: '0.6'
  exclude_repos:
    description: 'Comma-separated list of repository names to exclude (e.g., "repo1,repo2,repo3")'
    required: false
    default: ''
  max_repos:
    description: 'Maximum number of repositories to include in output'
    required: false
    default: '5'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Run adjacent
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ inputs.repo }}
        SIMILARITY_METHOD: ${{ inputs.similarity_method }}
        TOPIC_WEIGHT: ${{ inputs.topic_weight }}
        EXCLUDE_REPOS: ${{ inputs.exclude_repos }}
        MAX_REPOS: ${{ inputs.max_repos }}
      run: python ${{ github.action_path }}/.github/scripts/adjacent.py
      shell: bash
