name: 'Adjacent: Related Repos Recommender'
description: 'Auto-suggests and adds similar repositories to your README based on shared GitHub topics and README content similarity.'
author: 'Gaurav Sood'
branding:
  icon: link
  color: blue
inputs:
  repo:
    description: 'Target repository in owner/name format (e.g., soodoku/fastsql)'
    required: false
    default: ${{ github.repository }}
  token:
    description: 'GitHub token for API access'
    required: true
    default: ''
  similarity_method:
    description: 'Method to find similar repositories: topics, readme, or combined'
    required: false
    default: 'combined'
  topic_weight:
    description: 'Weight for topics in combined similarity method (0-1)'
    required: false
    default: '0.6'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install requests scikit-learn
      shell: bash
    - name: Run adjacent
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ inputs.repo }}
        SIMILARITY_METHOD: ${{ inputs.similarity_method }}
        TOPIC_WEIGHT: ${{ inputs.topic_weight }}
      run: python ${{ github.action_path }}/.github/scripts/adjacent.py
      shell: bash
