name: 'Adjacent: Related Repos Recommender'
description: 'Auto-suggests and adds similar repositories to your README based on shared GitHub topics.'
author: 'Your Name or Org'
branding:
  icon: link
  color: blue
inputs:
  repo:
    description: 'Target repository in owner/name format (e.g., soodoku/fastsql)'
    required: false
    default: ${{ github.repository }}
  token:
    description: 'GitHub token for API access'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install requests
      shell: bash
    - name: Run adjacent
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ inputs.repo }}
      run: python ${{ github.action_path }}/.github/scripts/adjacent.py
      shell: bash
