name: Adjacent Recommender
on:
  schedule:
    - cron: '0 5 * * 0'   # Every Sunday at 5am UTC
  workflow_dispatch:
jobs:
  update-adjacent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run adjacent recommender
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/adjacent.py
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update adjacent repos [automated]" || echo "No changes to commit"
          git push
